print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/s106020/Desktop/DJB-Game/Assets/Prefab/ayy.mb"`)
{		
	file -o "/Users/s106020/Desktop/DJB-Game/Assets/Prefab/ayy.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/s106020/Desktop/DJB-Game/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/s106020/Desktop/DJB-Game/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/s106020/Desktop/DJB-Game/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
